# 워크플로우의 이름
name: deploy service

on: 
  # 워크플로우 실행 조건 이벤트
  push:
    # 워크플로우 실행 조건 브랜치
    branches:
      - main

jobs:
    # 작업 이름
  ssh-agent:
      # 실행 환경
    runs-on: ubuntu-24.04

      # 어떤 작업을 하는지
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        # 작업의 이름
      - name: run ssh-agent, webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      # 깃허브 액션 워크스페이스 기준으로 EC2가 안전한지 확인해야함
      # finger-print
      # 원격 서버를 신회할 수 있는 서버로 등록하는 과정
      - name: Add Remote Server Fingerprint to Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts || true

      # ssh 접속 후 파일 생성
      - name: create file on remote server
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "touch 'test.txt'"
      
      # 원격 저장소에 있는 파일 EC2로 복사
      - name: copy file to remote server
        run: scp -P ${{ secrets.SSH_PORT }} README.md ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/ 

      # ssh 명령어의 가독성을 높히는 도구
      - name: Run remote command test
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          # SSH 연결 이후 실행할 명령어 목록
          script: |
            mkdir hello-dir
            cd hello-dir
            touch hello-EC2-1.txt
            touch hello-EC2-2.txt
            touch hello-EC2-3.txt

      # scp 명령의 가독성을 향상시키는 도구
      - name: Copy README.md file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          # 복사할 파일 이름, 여러개의 파일을 복사할 때는 쉼표(,)로 파일 이름을 구분한다
          source: "README.md" 
          # 원격 서버에 복사될 위치
          target: "~/"
