# 워크플로우의 이름
name: SSH

on: 
  # 워크플로우 실행 조건 이벤트
  push:
    # 워크플로우 실행 조건 브랜치
    branches:
      - main

jobs:
    # 작업 이름
  ssh-agent:
      # 실행 환경
    runs-on: ubuntu-24.04

      # 어떤 작업을 하는지
    steps:
        # 작업의 이름
      - name: run ssh-agent, webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      # 깃허브 액션 워크스페이스 기준으로 EC2가 안전한지 확인해야함
      # finger-print
      # 원격 서버를 신회할 수 있는 서버로 등록하는 과정
      - name: Add Remote Server Fingerprint to Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts || true

      # ssh 접속 후 파일 생성
      - name: create file on remote server
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 
