# 워크플로우의 이름
name: SSH

on: 
  # 워크플로우 실행 조건 이벤트
  push:
    # 워크플로우 실행 조건 브랜치
    branches:
      - main

  jobs:
    # 작업 이름
    ssh-agent:
      # 실행 환경
      runs-on: ubuntu-24.04

      # 어떤 작업을 하는지
      steps:
        # 작업의 이름
        - name: run ssh-agent, webfactory/ssh-agent
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
